### ISSUE TITLE
DeepL API 错误

### ISSUE THREAD

**Issue by Wolffy821** [Isayama-Kagura/TsubakiTranslator#11]
当我用DeepL API Pro的时候，会有“Response status code does not indicate success: 403 (Forbidden)”的错误。我尝试了Misaka，也一样存在这个错误。想问一下大佬对这个错误有头绪吗？

**Comment by Wolffy821** [comment]
我问过DeepL那边的客服，他说帮我在后台检查过，发现并没有异样。我也在WordPress和Python用过那个API，也根本没有问题。所以应该是大佬这边的程式有问题，可以帮忙修理一下吗？毕竟我花了6美刀买了DeepL API Pro...

**Comment by Isayama-Kagura** [comment]
可能因为我用的是free的url，我看看怎么修改一下

**Comment by Wolffy821** [comment]
麻烦你了。
因为Misaka那个作者说所有的Bug网上都有解决方法，要我自己找，就不肯回复我了。
于是我找替用的翻译器的时候就发现TsubakiTranslator，确实挺好用的，UI也很整洁，尤其翻译可以往回看真的很棒。
不过如果可以改翻译的颜色字体，还有让翻译的窗口隐形，让鼠标可以点击窗口后面的东西就更好了。
谢谢大佬！

**Comment by Isayama-Kagura** [comment]
有个问题，你测试时是挂着代理服务器的吗？我这边不开代理上不去deepl，而翻译器默认是没有用代理的。

> 不过如果可以改翻译的颜色字体，还有让翻译的窗口隐形，让鼠标可以点击窗口后面的东西就更好了。

字体颜色后面有空加上，窗口隐形会导致窗口无法拖动后来取消了，目前采用透明度调很低的方式

**Comment by Wolffy821** [comment]
我刚刚测试了一下，挂了日本的服务器，结果无论挂不挂代理也一样会产生错误。不知道是不是因为我在香港，我不开代理是能上去DeepL的。
要不我给你一下DeepL API Pro的API Key 试一试吧，反正我能刷新Key。
bea0ce4b-9031-b989-c1a6-4c6846c962f9

**Comment by Isayama-Kagura** [comment]
测了一下，是因为原先用的free的url失败了，pro就没事，暂时先换成pro的url了，重新去下载onedrive的文件试试

**Comment by Wolffy821** [comment]
可以用了，感谢！
