### ISSUE TITLE
请问程序如何使用？

### ISSUE THREAD

**Issue by GoodManWEN** [Isayama-Kagura/TsubakiTranslator#13]
第一次使用本程序，选中游戏进程后整体闪退，可能是什么原因导致的

**Comment by Isayama-Kagura** [comment]
设置好翻译API，先打开游戏，然后点注入进程，选择对应的游戏进程，选择正确的文本就可以翻译。

**Comment by GoodManWEN** [comment]
点击注入进程，选中游戏进程后整体闪退可能是什么原因导致的

**Comment by Isayama-Kagura** [comment]
之前也有给我反馈过类似的问题，但在我的电脑上测试同一款游戏也没有闪退，所以可能是电脑环境的问题？

你也可以把游戏名发给我测试一下

**Comment by GoodManWEN** [comment]
有无私信连接方式，游戏名不和说。

**Comment by Isayama-Kagura** [comment]
可私发邮箱

不过这种不一定会有解决办法，先尝试换别的电脑看是否有同样问题
