### ISSUE TITLE
[功能请求] 可否让翻译窗口自动吸附游戏界面

### ISSUE THREAD

**Issue by Yiak** [Isayama-Kagura/TsubakiTranslator#14]
让翻译窗口在使用鼠标拖动时可以自动吸附在游戏界面下侧边框下方或者上侧边框上方，同时自动匹配游戏界面边框的宽度。此后拖动游戏界面可以捆绑拖动翻译窗口。

**Comment by Isayama-Kagura** [comment]
因需要做的改动太大但实际作用较小，暂时没有实现该功能的计划
