### ISSUE TITLE
提取字符每个都重复了3次

### ISSUE THREAD

**Issue by Hickoo** [Isayama-Kagura/TsubakiTranslator#17]
已解决，设置重复字数，软件很稳定，我用御坂翻译在选择hook入口的时候就闪退

**Comment by Hickoo** [comment]
希望能把翻译源的红色字样移除，
![image](https://user-images.githubusercontent.com/26645719/158013846-274060b7-a646-439a-857d-bb74999a9dc0.png)
还有第一行一般是人名，希望能原样显示出来，只翻译人名下面的部分

**Comment by Isayama-Kagura** [comment]
不翻译人名可以设置正则替换，把人名替换成空字符就行

**Comment by Isayama-Kagura** [comment]
翻译源标识去掉不现实吧，怎么知道是对应的哪个api的结果
