### ISSUE TITLE
功能请求：对剪切板内容进行正则表达式查找和替换

### ISSUE THREAD

**Issue by powerRainy** [Isayama-Kagura/TsubakiTranslator#2]
感谢开发者的付出，我遇到一些特殊手段提取到剪贴板的文本带有少量乱码，希望增加通过正则表达式查找和替换剪贴板内容的功能。

**Comment by Isayama-Kagura** [comment]
我的理解是，剪贴板文本都是通过特定工具提取出来的文本，它们针对特定引擎进行优化，不会含有其他有规律的奇怪文本的。除了一些转义字符影响到API正常运行需要去除，别的应该都是必须翻译的正常文本吧。

会把文件路径也提取出来的，是用Textractor类的工具操作的吗？

**Comment by Isayama-Kagura** [comment]
如果只是想把`\n`之类的去掉，我就只用简单处理一下源文本，没必要再对翻译器做大的调整，避免出现太多使用概率比较低的功能

**Comment by powerRainy** [comment]
> 会把文件路径也提取出来的，是用Textractor类的工具操作的吗？

是

**Comment by Isayama-Kagura** [comment]
1.0版已添加

**Comment by powerRainy** [comment]
感谢作者大大的工作
