### ISSUE TITLE
[Feature request] 让hook文本选择界面的 Scrollbar 反白

### ISSUE THREAD

**Issue by Yiak** [Isayama-Kagura/TsubakiTranslator#20]
现在的 Scrollbar 是比背景色更深一点的深色，希望能改成和背景色反差更明显的灰色或浅白色。
有时候hook出来的文本很多，总是不能一眼看清滚动条在什么位置。

**Comment by Isayama-Kagura** [comment]
好想法，在最新的commit中已经做了滚动条样式调整
