### ISSUE TITLE
可以添加谷歌API接口吗？

### ISSUE THREAD

**Issue by vxhorse** [Isayama-Kagura/TsubakiTranslator#24]
感谢作者！
现在虽然有道公共的完全够用了，但有时还是容易触发请求上限。
作为备选我希望添加谷歌的API接口。

**Comment by Isayama-Kagura** [comment]
谷歌翻译效果其实不太行，而且很多前人开发过的免费接口都没多久就失效了。本项目也还留有一些免费接口，有需要就先用吧，自己是没动力去开发了
