### ISSUE TITLE
可否添加手动填入PID功能

### ISSUE THREAD

**Issue by vxhorse** [Isayama-Kagura/TsubakiTranslator#25]
在”注入进程“里选择游戏进程时需要根据游戏进程名来选择，这样在有时候（游戏没有进程名或进程名不为英文）时选择游戏比较困难。

能否加入手动填入PID功能，可以直接在选框里直接填入PID。

**Comment by Isayama-Kagura** [comment]
一般非英文进程名都会在最顶或者最底端，而且选过一次，在历史记录里会保存上一次的选择

**Comment by lilyblessing** [comment]
会有一些进程用的日文罗马音，而且还缩写；而在任务管理器中又是显示的日文原名。

这样就得在长长的列表里费老大劲去找：
『找日文名』无 ->『找罗马音全名』无 ->『找PID』列表显示不能拉大，一但眼花找个好几遍 终于找到了，发现是个莫名奇妙的缩写。

添加游戏后还不能加个备注命名，下次再打开不知道这是个啥游戏。

**Comment by lilyblessing** [comment]
> 会有一些进程用的日文罗马音，而且还缩写；而在任务管理器中又是显示的日文原名。
> 
> 这样就得在长长的列表里费老大劲去找： 『找日文名』无 ->『找罗马音全名』无 ->『找PID』列表显示不能拉大，一但眼花找个好几遍 终于找到了，发现是个莫名奇妙的缩写。
> 
> 添加游戏后还不能加个备注命名，下次再打开不知道这是个啥游戏。

关于备注希望能类似YUKI的界面那样自动按父文件夹名称备注，或者显示一下进程的完整路径，至少这样辨识度高一点能知道是个啥游戏。

**Comment by Isayama-Kagura** [comment]
首先还是吐槽下微软，我原来也想使用仿照YUKI那种输入+选择模式，不过wpf里没有这个控件，需要自己定制

其次你们找进程的方法可能也不太对，应该去『任务管理器』->『详细信息』里找，那个才是真正的进程名，然后历史记录里的游戏名是可以任意改的，不影响保存的进程注入历史

后续我再改进一下吧，在历史记录的游戏名保存进程的描述，这样也更通俗易懂

**Comment by Isayama-Kagura** [comment]
done
