### ISSUE TITLE
关于OCR功能的一点想法

### ISSUE THREAD

**Issue by Isayama-Kagura** [Isayama-Kagura/TsubakiTranslator#28]
从Windows10 Build 10240 开始，就自带支持ocr，在github上也有 https://github.com/zh-h/Windows.Media.Ocr.Cli 这种命令行项目，略微测试下发现效果还不错，所以想给翻译器加上这个功能。经过几天研究，发现有如下难点：

1、API调用。Tsubaki是使用wpf的，而ocr是uwp的api，而且只有win10环境才支持ocr，这样的话通过console调用是比较合适的方法。用console的话，是读取磁盘文件，还是直接读剪切板（之前尝试发现控制台读剪切板不好操作）？
2、图片截取。每次手动截图再识别，还是固定范围，固定范围的话是手动识别还是定时识别，定时截图如何保证不浪费api字数？

暂时想到这些，发出来看看有没有大佬解惑，如果能讨论出个比较可行的方案的话，后面会考虑摸出来

**Comment by luojunyuan** [comment]
拿到系统版本号确定是win10，再提供该功能，不用console。

某ocr翻译器是固定范围，定时截图，前后两次图片相似度低于某个界限，再OCR拿结果去翻译。

**Comment by Isayama-Kagura** [comment]
> 拿到系统版本号确定是win10，再提供该功能，不用console。

可以是这个逻辑，但要改项目配置，兼容不了win10以下。

> 某ocr翻译器是固定范围，定时截图，前后两次图片相似度低于某个界限，再OCR拿结果去翻译。

如果字体播放比较慢，或者背景一直有变化的，感觉也不太好使

**Comment by luojunyuan** [comment]
> > 拿到系统版本号确定是win10，再提供该功能，不用console。
> 
> 
> 
> 可以是这个逻辑，但要改项目配置，兼容不了win10以下。
> 
> 
> 
> > 某ocr翻译器是固定范围，定时截图，前后两次图片相似度低于某个界限，再OCR拿结果去翻译。
> 
> 
> 
> 如果字体播放比较慢，或者背景一直有变化的，感觉也不太好使

可以兼容win10以下的、在那些平台下你只要不去调用winrt相关的东西就好了

**Comment by Isayama-Kagura** [comment]
摸索了好久，选择范围自动截图功能还是不会弄，只能等大佬有缘来pr，我先躺了
