### ISSUE TITLE
用了pandaocr的截图 和sharex 的截图 

### ISSUE THREAD

**Issue by lhj5426** [Isayama-Kagura/TsubakiTranslator#29]
![image](https://user-images.githubusercontent.com/30548000/193843441-31875774-f2ff-4ba7-a54c-c6c78d239e1d.png)
一直在提示这个

**Comment by lhj5426** [comment]
软件好像自身没有截图功能 应该用什么样的工具才符号软件读取图片的要求？

**Comment by lhj5426** [comment]
因为这2个截图OCR工具 自身都有 固定范围截图 就不需要每次都框选 
每次按快捷键就可以直接截图了 所以用的这2个可十次里有8次会提示这个找不到项目

**Comment by Isayama-Kagura** [comment]
试一下sharex，应该是软件的原因，每次截图都会产生两次剪切板的事件，往前看翻译历史能找到正确的识别记录。我用qq和微信的截图就没这种现象

确实最好还是翻译器里自带一个截图功能，等后面有空再补上去了

**Comment by Isayama-Kagura** [comment]
最新一版弄好了自带的手动截图和自动截图功能，可以尝试一下

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/199680665-ce2ee9cb-6e2c-4ec3-800e-e6d94b77d59a.png)
给个反馈 比之前自己用第三方截图工具好多了
