### ISSUE TITLE
换行符处理问题

### ISSUE THREAD

**Issue by powerRainy** [Isayama-Kagura/TsubakiTranslator#3]
作者你好，我用特殊码提取部分游戏的文本时发现，提出的文本如果每一行行末有换行符则只能识别并翻译第一行，同一游戏通过剪贴板导入也存在这种情况。
如果通过内置的提取方法翻译界面原文和翻译都只有第一行，如果通过其他软件提取剪贴板导入则原文可以看到全部行，翻译仍只有第一行。
以上情况仅在我通过MisakaHookFinder自己找特殊码提取文本时出现，不需要特殊码和网上找的特殊码提取时均未出现以上情况，麻烦作者大大看看能不能修。
PS：其实如果实现了之前说的剪贴板正则表达式替换功能应该可以通过正则表达式把换行符干掉，这样就不用专门看这个bug了……吧

**Comment by Isayama-Kagura** [comment]
除了`\n`，一般还有什么特殊的转义字符吗，一起都去掉好了，应该不会影响原义。
还有关于上一个issue的，剪切板提取的文本除了转义字符，会出现其他需要自定义表达式才能处理的字符吗

**Comment by Isayama-Kagura** [comment]
通过进程注入游戏的是有正则表达式替换功能的，可以在历史游戏记录列表里找到

**Comment by powerRainy** [comment]
> 除了`\n`，一般还有什么特殊的转义字符吗，一起都去掉好了，应该不会影响原义。 还有关于上一个issue的，剪切板提取的文本除了转义字符，会出现其他需要自定义表达式才能处理的字符吗

目前没发现其他有影响的转义字符了。有的时候会把资源文件的路径也提取出来，所以想要通过正则表达式去掉。

> 通过进程注入游戏的是有正则表达式替换功能的，可以在历史游戏记录列表里找到

进程注入游戏遇到`\n`好像只能提取出第一行（至少翻译窗口的原文只显示第一行），这时候用正则表达式处理了也没有用。剪贴板导入倒是能显示完整原文，但只翻译第一行。

**Comment by Isayama-Kagura** [comment]
> 进程注入游戏遇到`\n`好像只能提取出第一行（至少翻译窗口的原文只显示第一行），这时候用正则表达式处理了也没有用。剪贴板导入倒是能显示完整原文，但只翻译第一行。

这是哪个游戏，用的提取工具是什么，对于注入进程提取的含有换行符目前想不到好的解决方法

**Comment by Isayama-Kagura** [comment]
重新发布了版本，自动去掉了剪切板文本的换行符

**Comment by powerRainy** [comment]
> 这是哪个游戏，用的提取工具是什么，对于注入进程提取的含有换行符目前想不到好的解决方法
提取用的MisakaHookFinder，本质也是Textractor。这种情况就遇到过一次，不去管他算了，只要剪贴板能用就行。
