### ISSUE TITLE
スタディ§ステディ2注入后非常卡

### ISSUE THREAD

**Issue by Laniaidea** [Isayama-Kagura/TsubakiTranslator#32]
测试了几个类似的翻译器 ，直接用Textractor注入或者用2020年的YUKI注入并不会卡顿，能正常选取文本，唯独Tsubaki会卡到不能选取文本
所以可能hook注入方式还能有优化的地方（虽然最佳方案应该是以Textractor注入+tsubaki监视剪切板啦）

**Comment by Isayama-Kagura** [comment]
游戏引擎的问题，tsubaki的hook方式底层就是textractor，因为不断有垃圾文本更新所以会卡。我试了下yuki虽然不卡，不过同样也获取不到正确的文本

**Comment by DDWSdwqdq** [comment]
说实话不更新HOOK模块，我真不建议做翻译器。新游戏一出就提取不出文本靠OCR连文本识别都不对还慢。 下载吧  我早就更新了这个钩子替换对应的X86的库就行了.
链接：https://pan.baidu.com/s/12J8eI5PJgSmod9yk7supbA 
提取码：52gk

**Comment by DDWSdwqdq** [comment]
> 

我自己逆向引擎添加的钩子，你以为.

**Comment by Isayama-Kagura** [comment]
更新了@DDWSdwqdq 的dll，问题已解决
