### ISSUE TITLE
1.0.5.4 OCR右键确认截图后崩溃

### ISSUE THREAD

**Issue by catshitz** [Isayama-Kagura/TsubakiTranslator#36]

**Comment by Isayama-Kagura** [comment]
这个只能等大佬帮忙了，看截图的逻辑有没有更好的实现方法

**Comment by Isayama-Kagura** [comment]
目前的想法是通过透明窗口进行截图，不过用PrintWindow或者BitBlt截出来的都是一片黑，不知是否有通过窗口handle来截图的方法，如有的话请看到的大佬提点

**Comment by luojunyuan** [comment]
ocr项目很多 建议你去翻下别人的源码。。

**Comment by Isayama-Kagura** [comment]
重写了OCR的截图逻辑，应该问题会少很多了
