### ISSUE TITLE
不知道是不是bug，翻译时某个翻译不翻译正要翻译的内容而翻译上一句的内容

### ISSUE THREAD

**Issue by wycstc353** [Isayama-Kagura/TsubakiTranslator#4]
不知道是不是bug，翻译时某个翻译不翻译正要翻译的内容而翻译上一句的内容，等一段时间后还是这样，某一个翻译翻译的是上一句的内容

**Comment by powerRainy** [comment]
大概是上游Textractor的问题，我在自己找特殊码的时候偶尔遇到过这种情况。

**Comment by Isayama-Kagura** [comment]
是提取的文本找不到当前的句子吧？

**Comment by wycstc353** [comment]
> 是提取的文本找不到当前的句子吧？

不是，因为是只有某个翻译不翻，别的翻译都是正常的

**Comment by Isayama-Kagura** [comment]
不是很懂，有没有截图说明一下

**Comment by wycstc353** [comment]
> 不是很懂，有没有截图说明一下

现在没这问题了，会自动刷新了，不知道是不是在你某次更新解决了
