### ISSUE TITLE
用监视剪切板翻译游戏的时候翻译器经常闪退

### ISSUE THREAD

**Issue by kannaginomori** [Isayama-Kagura/TsubakiTranslator#6]
我用监视剪切板翻译游戏的时候经常出现翻译着翻译着翻译器就突然闪退的情况，不知道是不是bug，用着用着莫名其妙就闪退了。
但是，闪退之后我重启翻译器和游戏，重启之后翻译器不会在之前闪退的位置闪退，重启之后在之前闪退的位置往后过几句文本就又闪退了。
总之就是用监视剪切板翻译游戏的时候翻译器经常闪退，不知道这是不是bug。

**Comment by Isayama-Kagura** [comment]
是什么游戏，用什么工具提取文本的

**Comment by kannaginomori** [comment]
游戏就是附件里那个aliceboys，它文本可以自动复制到剪切板，然后监视剪切板翻译，我这里游戏运行到附件图片那个位置，翻译器就闪退。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Isayama-Kagura/TsubakiTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Isayama-Kagura/TsubakiTranslator] 用监视剪切板翻译游戏的时候翻译器经常闪退 (Issue #6)





 
是什么游戏，用什么工具提取文本的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


从QQ邮箱发来的超大附件

aliceboys解包修改版游戏文本自动复制到剪贴板.rar (359.61M, 2021年12月14日 13:12 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=013461644d75b1d183fdf50442360517555003570700530848505656521b030a57034c055d050015530c07025602510d5252530064193759095d020106594e4bd8d6d198b4e88ffcd5d2b2aaab81f9fcd48ab6b0d2998f8cb3f2d4d9d8c2fbc1d5d14f1605443705&t=exs_ftn_download&code=e4add678

**Comment by Isayama-Kagura** [comment]
我玩到男主角出场了也没闪退...
是用的最新版的翻译器吗？

**Comment by kannaginomori** [comment]
还有这封邮件附件里的sweet这个游戏，跟之前发的aliceboys是一样的套路，问题也是一样的，它俩的问题都是：在全屏运行游戏的情况下开监视剪切板翻译，才翻译了几句话翻译器就闪退，闪退之后保持全屏运行游戏的同时重启翻译器打开监视剪贴板翻译，又是才翻译了几句话翻译器就闪退。全屏运行这俩游戏的情况下开监视剪切板翻译，翻译器就极其频繁的闪退；但如果窗口运行这俩游戏不开全屏，窗口运行游戏的情况下开监视剪切板翻译，翻译器就很稳定不会闪退，我估计是翻译器适配全屏游戏的问题。


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Isayama-Kagura/TsubakiTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Isayama-Kagura/TsubakiTranslator] 用监视剪切板翻译游戏的时候翻译器经常闪退 (Issue #6)





 
是什么游戏，用什么工具提取文本的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


从QQ邮箱发来的超大附件

純正優男Sweet&amp;Bitter v1.2解包修改版游戏文本自动复制到剪贴板.rar (61.44M, 2021年12月14日 14:19 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=45623065ef8d4b9ed7aba4051664514d5253545d000557561c5200565549575b53031d5d0753524f5304075152545b0609500404305b63deb2b7cde6aea0b3314607551116260a164507424546554d508c808099e0badba68184e3abffd3ada680dce7b186cbdbd6e7a485d88c90af9b81871e175116635f&t=exs_ftn_download&code=1b0e0dcb

**Comment by kannaginomori** [comment]
我也是用的最新版1.0.0，然后我刚刚发现问题应该是翻译器不适配全屏运行游戏，全屏运行我发的两个游戏的情况下开启监视剪切板翻译器就频繁闪退，
窗口运行游戏不开全屏就万事大吉。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Isayama-Kagura/TsubakiTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Isayama-Kagura/TsubakiTranslator] 用监视剪切板翻译游戏的时候翻译器经常闪退 (Issue #6)





 
我玩到男主角出场了也没闪退...
 是用的最新版的翻译器吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kannaginomori** [comment]
我刚刚折腾了半天发现：在两个游戏的设置里把文本速度开到最高并且秒点文本（不看内容直接半秒一句话的点），监视剪切板翻译的时候翻译器就有概率闪退，如果文本速度只开一半并且不要那么快地点文本，或者文本速度开到最高但不要那么快地点文本，就比较稳定不会闪退，同时窗口运行游戏比全屏运行游戏监视剪切板稳定，我刚刚全屏运行游戏翻译器也有概率闪退。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Isayama-Kagura/TsubakiTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Isayama-Kagura/TsubakiTranslator] 用监视剪切板翻译游戏的时候翻译器经常闪退 (Issue #6)





 
我玩到男主角出场了也没闪退...
 是用的最新版的翻译器吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kannaginomori** [comment]
新发现：{我在两个游戏[附件里示例图以外的图片]的位置点击翻译器主界面的【监视剪切板】并点击确定出现翻译窗口，或者在游戏运行的过程中（已经玩了一段时间过了一些游戏文本的位置，如示例图）点击翻译器主界面的【监视剪切板】并点击确定出现翻译窗口}，{}里的情况下无论是窗口游戏还是全屏游戏，无论点击游戏文本的速度是快是慢，翻译了一些句子之后翻译器都必然闪退。
但我先点击翻译器主界面的【监视剪切板】并点击确定出现翻译窗口，之后再双击游戏程序启动游戏并运行，先打开监视剪切板的翻译窗口然后再启动并运行游戏的情况下，翻译器比{}里的情况下要稳定得多，运行游戏翻译句子的过程中翻译器不会闪退。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Isayama-Kagura/TsubakiTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Isayama-Kagura/TsubakiTranslator] 用监视剪切板翻译游戏的时候翻译器经常闪退 (Issue #6)





 
我玩到男主角出场了也没闪退...
 是用的最新版的翻译器吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


从QQ邮箱发来的超大附件

aliceboys开头画面.png (52.4K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=78666331ba4ccfc9d4aff7511f620219560053070b5b06571f0255545b4f040f53524e500803521b0a5351050c52080353555a04397730575e0f00545b0d49458dccae8682cff3d01c160d56395f&t=exs_ftn_download&code=2fc19b06




aliceboys游戏封面.png (1.39M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2f6665315ab3dacc83aff1511561011c0753075304580555485f5554014c0756535048500055571e060455550b5357550154500833743352090f0654510e4a40b6a8aa868483f0d54b160b56335c&t=exs_ftn_download&code=efe13a33




sweet&amp;bitter游戏封面.png (1.24M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7c373864a057dfc9d7feac044362011954005955530051501c535901534f07045403155d51520b1b5001005152510700540e5b50657a334546525d1043005a4245524ab7abad8481d3f4de4a150c54360c&t=exs_ftn_download&code=178deb36




sweet&amp;bitter选择主人公.png (772.5K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7d64666341dac1cfd4adf2034034001f56015153505707061f055f065719060203534b015651021d020552055651000705520254662e32434501031740565b44460114b2c7e0c3e6c5acaddacd1a425e55645b&t=exs_ftn_download&code=2dfcf420




sweet&amp;bitter主人公取名.png (904.9K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2b38336541ec97cd82f1a7051630541d005b505600075300490e0453071d520b5c011e5c0903501f505c0407510751035d005504302a6641135d561116520f46105d41b3c7f8ad8bcff092a6cb1e165c03380e&t=exs_ftn_download&code=d83e00f2




示例图.png (914.5K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=09313131d8d3c0cdd0f8a5511f66031d575555555a5153071b550205084b050705001c505c56031f015402025d0453050e045354396c31f888f1ccfc8548415c51310c&t=exs_ftn_download&code=61119f12

**Comment by kannaginomori** [comment]
我的天，折腾半天我终于把我这里翻译器闪退的原因查出来了，总结一下就是：先开游戏后开监视剪切板的翻译窗口则翻译器必然翻译一些句子就闪退，先开监视剪切板的翻译窗口后开游戏则翻译器顺利翻译。
就我遇到的情况而言，我这里翻译器闪退与否只取决于我是先开游戏还是先开监视剪切板的翻译窗口。至于游戏是全屏还是窗口，游戏设置里的文本速度是快是慢，点击游戏文本的速度是半秒点一句文本还是一分钟点一句文本，这些其实都跟翻译器闪退毫无关系，我之前觉得这些跟翻译器闪退有关纯粹是我想多了。
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Isayama-Kagura/TsubakiTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Isayama-Kagura/TsubakiTranslator] 用监视剪切板翻译游戏的时候翻译器经常闪退 (Issue #6)





 
是什么游戏，用什么工具提取文本的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Isayama-Kagura** [comment]
我电脑上无论谁先谁后都没有闪退。。。无法复现所以解决不了
