### ISSUE TITLE
1.01版是没有原来的窗口化了吗？现在要么是最大化，要么是只有一个小框

### ISSUE THREAD

**Issue by wycstc353** [Isayama-Kagura/TsubakiTranslator#7]
1.01版是没有原来的窗口化了吗？现在要么是最大化，要么是只有一个小框
![image](https://user-images.githubusercontent.com/39401653/143729832-d38410c2-1c53-42c1-b960-a2e501a7f219.png)

**Comment by Isayama-Kagura** [comment]
大概只是初始化时出了点问题，拖动边框把它拉回正常应该就没问题了

**Comment by Isayama-Kagura** [comment]
增加了窗口最小宽度和高度
