### ISSUE TITLE
可以出个不带 dotnet runtime 的版本吗

### ISSUE THREAD

**Issue by Landius** [Isayama-Kagura/TsubakiTranslator#8]
系统里装有 runtime 的话，感觉有点重复了呢 <3

**Comment by Isayama-Kagura** [comment]
已添加，没办法微软自己的系统都不自带runtime

**Comment by Yiak** [comment]
TsubakiTranslator_WithoutRT.rar 不兼容 dotnet runtime 6 (arm64)，必须再多安装一份 dotnet runtime 6 (x64)才能打开。请问可以编译个arm64的版本吗？谢谢。

**Comment by Isayama-Kagura** [comment]
> TsubakiTranslator_WithoutRT.rar 不兼容 dotnet runtime 6 (arm64)，必须再多安装一份 dotnet runtime 6 (x64)才能打开。请问可以编译个arm64的版本吗？谢谢。

把目标改成了可移植的，再试试

**Comment by Yiak** [comment]
> > TsubakiTranslator_WithoutRT.rar 不兼容 dotnet runtime 6 (arm64)，必须再多安装一份 dotnet runtime 6 (x64)才能打开。请问可以编译个arm64的版本吗？谢谢。
> 
> 把目标改成了可移植的，再试试

还是不成功，表现为程序双击后无法运行（什么都没发生）。
可能是因为转译到arm后寻找的依然是x64版本runtime。
不过不是什么大问题，安装好x64版runtime后可以顺利运行，先这样吧～

**Comment by Isayama-Kagura** [comment]
> 还是不成功，表现为程序双击后无法运行（什么都没发生）。
> 可能是因为转译到arm后寻找的依然是x64版本runtime。
> 不过不是什么大问题，安装好x64版runtime后可以顺利运行，先这样吧～

可能是你之前的runtime是.net core的，我现在用的是.net6的，因为我现在也打不开基于.net core的无依赖软件了
